/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameResult = IDL.Record({
  'playerNumbers' : IDL.Vec(IDL.Nat),
  'player' : IDL.Principal,
  'matches' : IDL.Nat,
  'computerNumbers' : IDL.Vec(IDL.Nat),
  'isWin' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getPlayerResults' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GameResult)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameResult = IDL.Record({
    'playerNumbers' : IDL.Vec(IDL.Nat),
    'player' : IDL.Principal,
    'matches' : IDL.Nat,
    'computerNumbers' : IDL.Vec(IDL.Nat),
    'isWin' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getPlayerResults' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GameResult)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };